### ISSUE TITLE
Slow working of bot 

### ISSUE THREAD

**Issue by op-coder482** [op-coder482/Black-Thunder-#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots(if any)**

**Additional context**

**Comment by op-coder482** [comment]
Abey BSDK

**Comment by op-coder482** [comment]
Shhhhh chup

**Comment by luluop** [comment]
LMAO WTF

**Comment by luluop** [comment]
![Uploading IMG_20210109_081300_174.jpg…]()

**Comment by luluop** [comment]
@IGUNUBLUE BSDK hai

**Comment by luluop** [comment]
Maa Chudao sb maa

**Comment by pogonoob** [comment]
Lol

**Comment by pogonoob** [comment]
Nubz
